language: scala
scala:
  - 2.10.2
  - 2.11.0
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
services:
  - postgresql
  - mysql
before_script:
  - ./script/prepare_build.sh

notifications:
  email:
    - linhares.mauricio@gmail.com
